### ISSUE TITLE
nstimer崩溃

### ISSUE THREAD

**Issue by Bretra** [sunday1990/BayMaxProtector#4]
引入现有项目中，奔溃在nstimer这里， BMP_SuppressPerformSelectorLeakWarning(
               [_aTarget performSelector:_aSelector];
            ); 
Thread 1: EXC_BAD_ACCESS (code=1, address=0xd69546e88)错误

**Comment by sunday1990** [comment]
你可以先暂时关闭timer防护，我再检查一下代码

**Comment by Bretra** [comment]
我这边并如果去掉timer防护，单例类里面的timer就会造成出错，原本运行正确




| |
楚永磊
邮箱：yongleichu@163.com
|

签名由 网易邮箱大师 定制

在2018年03月01日 13:30，ccSunday 写道：

你可以先暂时关闭timer防护，我再检查一下代码

**Comment by sunday1990** [comment]
你先这样试试，看能不能先把tiemr关掉，并且不影响其他的
    [BayMaxProtector openProtectionsOn:BayMaxProtectionTypeAll];
    [BayMaxProtector closeProtectionsOn:BayMaxProtectionTypeTimer];

**Comment by Bretra** [comment]
我试一下




| |
楚永磊
邮箱：yongleichu@163.com
|

签名由 网易邮箱大师 定制

在2018年03月01日 13:36，ccSunday 写道：
你先这样试试，看能不能先把tiemr关掉，并且不影响其他的
[BayMaxProtector openProtectionsOn:BayMaxProtectionTypeAll];
[BayMaxProtector closeProtectionsOn:BayMaxProtectionTypeTimer];

**Comment by Bretra** [comment]
这样子可以过滤掉nstimer，但防护不管用了
 NSMutableArray *arr = [NSMutableArray array];
    [arr replaceObjectAtIndex:1 withObject:@"1"];
    CLog(@"%@", arr);

出现这个：Thread 1: breakpoint 1.2

**Comment by sunday1990** [comment]
你暂时先把timer关掉，这个不会影响其他的防护，你刚提出的这个数组的崩溃，是因为没有把数组的这种方法加进去，只加了一部分，我等稍后在完善一下，感谢提出宝贵意见，一起完善这个库。

**Comment by Bretra** [comment]
嗯 好 谢了




| |
楚永磊
邮箱：yongleichu@163.com
|

签名由 网易邮箱大师 定制

在2018年03月01日 13:49，ccSunday 写道：

你暂时先把timer关掉，这个不会影响其他的防护，你刚提出的这个数组的崩溃，是因为没有把数组的这种方法加进去，只加了一部分，我等稍后在完善一下，感谢提出宝贵意见，一起完善这个库。

**Comment by sunday1990** [comment]
你好，今天提的两个问题，一个是timer崩溃，另一个是数组replaceObjectAtIndex方法没有进行防护的问题已经解决了，可以更新下最新的代码试试，如果有问题，还请及时反馈

**Comment by ChiHoc** [comment]
Fixed NSTimer schedule crash #8

**Comment by sunday1990** [comment]
这个问题已修复
